Fix ReferenceError: exports is not defined
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/lib/homebridge/node_modules/homebridge-blueconnect-v2/package.json' contains "type": "module".